name: rece
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=1.23.5,<2.3
  - scipy>=1.14,<1.15
  - pillow>=10
  - requests>=2.32
  - vtk>=9.3
  - pip
  - pip:
      - pywebview>=6.2,<7
